Material UI - Styling, Dialog, and Form Validation(#40835)
nxfareed/javascript-client pull request #10
Opened 2020-03-31 15:40 UTC by nxfareed

Link to the task: https://redmine.successive.tech/issues/40835

2020-03-31 22:01 UTC, Prabal555 requested changes

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +import PersonIcon from '@material-ui/icons/Person';
use a single import statement for all this.

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +import VisibilityOff from '@material-ui/icons/VisibilityOff';
use a single import statement for all this

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +    }
use try-catch and async-await instead

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +    this.hasErrors();
Why was this called hasError()

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +                error={!!error.password}
why !! ?

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +                error={!!error.email}
why !!

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +                error={!!error.confirmPassword}
why '!!' ?

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +export default withStyles(useStyles)(AddDialog);
Please make sure that export default is the last statement of the file

2020-03-31 22:01 UTC, Prabal555 commented on src/pages/Trainee/Trainee.jsx
> +import AddDialog from './Components/AddDialog/index';
the Components folder should be of lower case components

2020-04-26 03:21 UTC, nxfareed commented on src/pages/Trainee/Components/AddDialog/AddDialog.jsx
> +    this.hasErrors();
To disable the submit button first and then to enable it after all the conditions are fulfilled.

2020-06-01 05:59 UTC, merged