feat: Add Pagination in Table(#41191)
nxfareed/javascript-client pull request #16
Opened 2020-06-23 05:19 UTC by nxfareed

2020-06-24 17:34 UTC, Prabal555 commented
Some issues:

- Trainee list is not updating after on edit button.
- As mentioned in the P.R changes please use index file to export and import.

2020-06-24 17:34 UTC, Prabal555 requested changes

2020-06-24 17:34 UTC, Prabal555 commented on src/pages/Trainee/Components/EditDialog/EditDialog.jsx
> +            });
Please don't do setState in a loop, since it caused re rendering, make sure to make the object that we use to construct the object first and then do setState as less as possible

2020-06-24 17:34 UTC, Prabal555 commented on src/pages/Trainee/Components/RemoveDialog/RemoveDialog.jsx
> +import DialogTitle from "@material-ui/core/DialogTitle";
Should have been a single import statement

2020-06-24 17:34 UTC, Prabal555 commented on src/pages/Trainee/Components/RemoveDialog/RemoveDialog.jsx
> +    <div>
Is there a need for a div here ?

2020-06-24 17:34 UTC, Prabal555 commented on src/pages/Trainee/TraineeList.jsx
> +import RemoveDialog from "./Components/RemoveDialog/RemoveDialog";
import from the index file

2020-06-24 17:34 UTC, Prabal555 commented on src/pages/Trainee/TraineeList.jsx
>  import Table from "./Components/Table/Table";
import from the index file from above

2020-06-24 17:34 UTC, Prabal555 commented on src/pages/Trainee/Components/EditDialog/EditDialog.jsx
> +    const { open, onClose, onSubmit, data } = this.props;
destructure could have been the part of the same line

2020-06-24 17:34 UTC, Prabal555 commented on src/pages/Trainee/TraineeList.jsx
> +      RemoveOpen,
they should not be in pascal case

2020-06-25 17:21 UTC, nxfareed commented on src/pages/Trainee/Components/RemoveDialog/RemoveDialog.jsx
> +    <div>
No

2020-06-30 07:15 UTC, merged